language: python
sudo: false
# Add or remove version for match with Travis support
python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6
    - pypy
    - pypy3
os:
  - linux

# Note: graphviz is needed for grapgs embedded in the docs
addons:
  apt:
    packages:
      - graphviz
      - libvirt-dev

matrix:
  fast_finish: true
  include:
    - env: ENV=checks
      python: 2.7
      before_script: TOX_ENV=checks
    - env: ENV=lint
      python: 2.7
      before_script: TOX_ENV=lint
    - env: ENV=pylint
      python: 2.7
      before_script: TOX_ENV=pylint
    - env: ENV=coverage
      python: 2.7
      before_script: TOX_ENV=coverage-travis
    - env: ENV=docs
      python: 3.5
      before_script: TOX_ENV=docs-travis
      # Note: graphviz is needed for grapgs embedded in the docs
      addons:
        apt:
          packages:
            - graphviz
            - gcc
            - libvirt-dev
      # Trigger ReadTheDocs build on docs builder
      after_success:
        - ./contrib/trigger_rtd_build.py 8284

install:
  - pip install --upgrade "pip==9.0.1"
  - pip install "virtualenv==15.1.0"
  - pip install "tox==2.8.2"
  - TOX_ENV=py$TRAVIS_PYTHON_VERSION

script:
  - tox -e $TOX_ENV

cache:
  apt: true
  directories:
    - $HOME/.cache/pip # pip cache

notifications:
  # Disabled until ASF switches to new mailing list software
  # when we can whitelist addresses
  #email:
  #  - "notifications@libcloud.apache.org"
  irc:
    - "chat.freenode.net#libcloud"
