language: python
# Add or remove version for match with Travis support
python:
    - 2.6
    - 2.7
    - 3.2
    - 3.3
    - 3.4
    - 3.5
    - "pypy"
sudo: false
os:
  - linux
  - osx
env:

matrix:
  fast_finish: true
  allow_failures:
    - os: osx
  include:
    - python: 2.7
      env: ENV=lint
      before_script: TOX_ENV=lint
    - python: 2.7
      env: ENV=docs
      before_script: TOX_ENV=docs-travis
      before_install:
        - easy_install graphviz

install:
  - TOX_ENV=py$TRAVIS_PYTHON_VERSION
  - pip install tox

script:
  - tox -e $TOX_ENV

notifications:
  email:
    - notifications@libcloud.apache.org
  irc:
    - "chat.freenode.net#libcloud"
